permalink: /:title/
base: http://www.aniart.eu
name: ANI Art

markdown: kramdown
highlighter: rouge

redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: "_posts/en"
    values:
      lang: en
      layout: default
      locale: en_US
  -
    scope:
      path: "_posts/ru"
    values:
      lang: ru
      layout: default
      locale: ru_RU
  -
    scope:
      path: "_posts/lv"
    values:
      lang: lv
      layout: default
      locale: lv_LV
  -
    scope:
      path: "_posts/en/pages"
    values:
      lang: en
      layout: default
      locale: en_US
      type: pages
      desc: "Latvian Artist"
      keywords: "astrology, impressionism, landscape, scenery, talisman-painting"
  -
    scope:
      path: "_posts/ru/pages"
    values:
      lang: ru
      layout: default
      locale: ru_RU
      type: pages
      desc: "Латвийская художница"
      keywords: "астрология, импрессионизм, пейзаж, картина-талисман"
  -
    scope:
      path: "_posts/lv/pages"
    values:
      lang: lv
      layout: default
      locale: lv_LV
      type: pages
      desc: "Latvijas māksliniece"
      keywords: "astroloģija, impresionisms, ainava, glezna-talismans, jūras ainava"