permalink: /:title/
base: http://www.aniart.eu
name: ANI Art

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
      desc: buga
  -
    scope:
      path: _posts/ru
    values:
      lang: ru
  -
    scope:
      path: _posts/lv
    values:
      lang: lv
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Desc English"
      keywords: "buy painting, paintings for sale, interior painting, interior, home design, painting, astrology, impressionism, Riga, Latvia, palette knife, marine, sea-piece, portrait in oils, commit to paint a picture, landscape, scenery, talisman-painting, talisman-picture"
  -
    scope:
      path: _posts/ru/pages
    values:
      type: pages
      desc: "TBD Russian"
      keywords: "купить картину; продажа картин; интерьерная живопись; интерьер, дизайн дома, живопись, астрология, импрессионизм, Рига, Латвия, мастихин, море картины, портрет маслом, заказать портрет масло, пейзаж, картина-талисман, морской пейзаж"
  -
    scope:
      path: _posts/lv/pages
    values:
      type: pages
      desc: "TBD Latvian"
      keywords: "buy painting, paintings for sale, interior painting, interior, home design, painting, astrology, impressionism, Riga, Latvia, palette knife, marine, sea-piece, portrait in oils, commit to paint a picture, landscape, scenery, talisman-painting, talisman-picture"
